# Site settings
title: Arjun's Portfolio
description: Arjun full stack web developer portfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Arjun Ankathatti Chandrashekara
user_description: I am a Full Stack Software Developer with 3 years of experience in Web Application Development. I have hands-on experience in programming with object-oriented language Java and frameworks like Struts2, Hibernate, AngularJS. This has instilled strong programming and analytical skills in me. I have also worked on web scripting, relational database, and frontend GUI development using HTML5, JavaScript, Jquery, CSS, SASS and Bootstrap 4.
user_title: Full Stack Software Developer
email: aacwb@mail.missouri.edu
twitter_username: lorem_ipsum
github_username:  acarjungowda
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: "UA-125656513-1"

exclude: ['package.json', 'src' , 'node_modules']
